import JSZip from 'jszip';
import type { BillingZipKind, BillingLanguage } from '../data/types';

export interface PlanSummary {
  name: string;
  billingModel: string;
  price: string;
  cadence: string;
  notes: string;
}

export interface BillingZipContext {
  offerName: string;
  offerTypeName: string;
  billingZipKind: BillingZipKind;
  billingModelLabels: string[];
  plans: PlanSummary[];
  /** Implementation language for code files (webhook/metering). Defaults to 'node'. */
  language: BillingLanguage;
}

export function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function languageLabel(language: BillingLanguage): string {
  return language === 'csharp' ? 'C# (.NET 8 / ASP.NET minimal API)' : 'Node.js (Express)';
}

function billingReadme(ctx: BillingZipContext): string {
  return `# Billing starter — ${ctx.offerName || ctx.offerTypeName}

Offer type: **${ctx.offerTypeName}**
Billing template: **${ctx.billingZipKind}**
Implementation language: **${languageLabel(ctx.language)}**

Billing models selected:
${ctx.billingModelLabels.map((b) => `- ${b}`).join('\n') || '- (none selected)'}

## Plans
${
  ctx.plans.length
    ? ctx.plans
        .map(
          (p) =>
            `- **${p.name}** — ${p.billingModel} — ${p.price || 'price TBD'} / ${
              p.cadence || 'cadence TBD'
            }${p.notes ? ` — ${p.notes}` : ''}`
        )
        .join('\n')
    : '- (no plans defined yet)'
}

## What's in this starter
This package gives you a running start on the billing & costing integration your
offer needs in Microsoft commercial marketplace / Partner Center. Review every file,
replace placeholders, and wire it into your own service.

> Generated by the Microsoft Marketplace Offer Wizard. Not an official Microsoft template.
`;
}

function plansJson(ctx: BillingZipContext): string {
  return JSON.stringify(
    {
      offer: ctx.offerName,
      offerType: ctx.offerTypeName,
      billingTemplate: ctx.billingZipKind,
      billingModels: ctx.billingModelLabels,
      plans: ctx.plans
    },
    null,
    2
  );
}

const SAAS_PACKAGE_JSON = `{
  "name": "saas-billing-starter",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node src/webhook.js"
  },
  "dependencies": {
    "@azure/identity": "^4.4.1",
    "express": "^4.19.2"
  }
}
`;

const SAAS_ENV_EXAMPLE = `# Microsoft Entra app registration used to call the Marketplace APIs
AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_SECRET=replace-me

# Local webhook port
PORT=3000
`;

const SAAS_METERING_JS = `// metering.js
// Azure Marketplace Metering Service - emit usage events for metered (pay-as-you-go) dimensions.
// Docs: https://learn.microsoft.com/partner-center/marketplace/marketplace-metering-service-apis
import { ClientSecretCredential } from '@azure/identity';

// Fixed resource/audience for the commercial marketplace metering API.
const MARKETPLACE_SCOPE = '20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default';
const USAGE_EVENT_URL =
  'https://marketplaceapi.microsoft.com/api/usageEvent?api-version=2018-08-31';

const credential = new ClientSecretCredential(
  process.env.AZURE_TENANT_ID,
  process.env.AZURE_CLIENT_ID,
  process.env.AZURE_CLIENT_SECRET
);

async function getToken() {
  const token = await credential.getToken(MARKETPLACE_SCOPE);
  if (!token) throw new Error('Could not acquire a marketplace access token.');
  return token.token;
}

/**
 * Emit a single metered usage event.
 * @param {object} evt
 * @param {string} evt.resourceId  SaaS subscription id (or managed-app resourceUsageId)
 * @param {string} evt.planId      Plan the customer is on
 * @param {string} evt.dimension   Metered dimension id from your plan (e.g. "api_calls")
 * @param {number} evt.quantity    Units consumed since the last event
 */
export async function emitUsageEvent({ resourceId, planId, dimension, quantity }) {
  const accessToken = await getToken();
  const res = await fetch(USAGE_EVENT_URL, {
    method: 'POST',
    headers: {
      Authorization: \`Bearer \${accessToken}\`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      resourceId,
      planId,
      dimension,
      quantity,
      effectiveStartTime: new Date().toISOString()
    })
  });

  if (!res.ok) {
    throw new Error(\`Usage event failed: \${res.status} \${await res.text()}\`);
  }
  return res.json();
}

/**
 * Batch up to 25 usage events in a single call.
 * Docs: .../marketplace-metering-service-apis#metered-billing-batch-usage-event
 */
export async function emitBatchUsage(events) {
  const accessToken = await getToken();
  const res = await fetch(
    'https://marketplaceapi.microsoft.com/api/batchUsageEvent?api-version=2018-08-31',
    {
      method: 'POST',
      headers: {
        Authorization: \`Bearer \${accessToken}\`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ request: events })
    }
  );
  if (!res.ok) {
    throw new Error(\`Batch usage failed: \${res.status} \${await res.text()}\`);
  }
  return res.json();
}
`;

const SAAS_WEBHOOK_JS = `// webhook.js
// SaaS fulfillment v2 webhook - handle subscription lifecycle events.
// Docs: https://learn.microsoft.com/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-webhook
import express from 'express';
import { emitUsageEvent } from './metering.js';

const app = express();
app.use(express.json());

app.post('/webhook', async (req, res) => {
  const event = req.body; // { id, action, subscriptionId, planId, quantity, timeStamp, status }
  console.log('Marketplace webhook:', event.action, event.subscriptionId);

  // IMPORTANT: validate the event by calling the GET Operation API before acting on it.
  // Then ACK by PATCHing the operation to Success/Failure.

  switch (event.action) {
    case 'Subscribe':
      // Provision the customer, store subscriptionId -> tenant mapping.
      break;
    case 'Unsubscribe':
      // Deprovision / disable access.
      break;
    case 'ChangePlan':
      // Update entitlements to the new plan.
      break;
    case 'ChangeQuantity':
      // Update seat count.
      break;
    case 'Suspend':
      // Payment failed - soft-disable access.
      break;
    case 'Reinstate':
      // Payment recovered - restore access.
      break;
    case 'Renew':
      // Subscription renewed.
      break;
    default:
      console.warn('Unhandled action:', event.action);
      break;
  }

  res.sendStatus(200);
});

// Example: report metered usage on a schedule (call from your billing job).
export async function reportDailyUsage(subscriptionId, planId) {
  await emitUsageEvent({
    resourceId: subscriptionId,
    planId,
    dimension: 'api_calls',
    quantity: 0 // replace with real metered quantity
  });
}

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(\`SaaS fulfillment webhook on :\${port}\`));
`;

const SAAS_PRICING_JSON = `{
  "$comment": "Reference shape for plans & metered dimensions. Configure the real values in Partner Center > Plan overview > Pricing and availability.",
  "plans": [
    {
      "planId": "starter",
      "displayName": "Starter",
      "billingTerm": { "value": 1, "type": "Month" },
      "recurrentPrice": { "priceInputOption": "flat", "flatPrice": 0 },
      "dimensions": [
        {
          "id": "api_calls",
          "displayName": "API calls",
          "unitOfMeasure": "calls",
          "pricePerUnit": 0.001,
          "includedQuantity": 10000,
          "overageBilling": true
        }
      ]
    }
  ]
}
`;

// ---------------------------------------------------------------------------
// C# (.NET 8) variants
// ---------------------------------------------------------------------------

const CSHARP_WEB_CSPROJ = `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BillingStarter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
</Project>
`;

const CSHARP_CONSOLE_CSPROJ = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BillingStarter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
</Project>
`;

const CSHARP_METERING_CS = `// Metering.cs
// Azure Marketplace Metering Service - emit usage events for metered (pay-as-you-go) dimensions.
// Docs: https://learn.microsoft.com/partner-center/marketplace/marketplace-metering-service-apis
using System.Net.Http.Json;
using Azure.Core;
using Azure.Identity;

namespace BillingStarter;

/// <param name="ResourceId">SaaS subscription id (or managed-app resourceUsageId)</param>
/// <param name="PlanId">Plan the customer is on</param>
/// <param name="Dimension">Metered dimension id from your plan (e.g. "api_calls")</param>
/// <param name="Quantity">Units consumed since the last event</param>
public record UsageEvent(string ResourceId, string PlanId, string Dimension, double Quantity);

public class MeteringClient
{
    // Fixed resource/audience for the commercial marketplace metering API.
    private const string MarketplaceScope = "20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default";
    private const string UsageEventUrl =
        "https://marketplaceapi.microsoft.com/api/usageEvent?api-version=2018-08-31";
    private const string BatchUsageUrl =
        "https://marketplaceapi.microsoft.com/api/batchUsageEvent?api-version=2018-08-31";

    private readonly ClientSecretCredential _credential;
    private readonly HttpClient _http = new();

    public MeteringClient(string tenantId, string clientId, string clientSecret)
    {
        _credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
    }

    private async Task<string> GetTokenAsync()
    {
        var token = await _credential.GetTokenAsync(
            new TokenRequestContext(new[] { MarketplaceScope }));
        return token.Token;
    }

    /// <summary>Emit a single metered usage event.</summary>
    public async Task<string> EmitUsageEventAsync(UsageEvent evt)
    {
        var accessToken = await GetTokenAsync();
        using var req = new HttpRequestMessage(HttpMethod.Post, UsageEventUrl);
        req.Headers.Authorization = new("Bearer", accessToken);
        req.Content = JsonContent.Create(new
        {
            resourceId = evt.ResourceId,
            planId = evt.PlanId,
            dimension = evt.Dimension,
            quantity = evt.Quantity,
            effectiveStartTime = DateTime.UtcNow
        });
        var res = await _http.SendAsync(req);
        var body = await res.Content.ReadAsStringAsync();
        if (!res.IsSuccessStatusCode)
            throw new InvalidOperationException($"Usage event failed: {(int)res.StatusCode} {body}");
        return body;
    }

    /// <summary>Batch up to 25 usage events in a single call.</summary>
    public async Task<string> EmitBatchUsageAsync(IEnumerable<UsageEvent> events)
    {
        var accessToken = await GetTokenAsync();
        using var req = new HttpRequestMessage(HttpMethod.Post, BatchUsageUrl);
        req.Headers.Authorization = new("Bearer", accessToken);
        req.Content = JsonContent.Create(new
        {
            request = events.Select(e => new
            {
                resourceId = e.ResourceId,
                planId = e.PlanId,
                dimension = e.Dimension,
                quantity = e.Quantity,
                effectiveStartTime = DateTime.UtcNow
            })
        });
        var res = await _http.SendAsync(req);
        var body = await res.Content.ReadAsStringAsync();
        if (!res.IsSuccessStatusCode)
            throw new InvalidOperationException($"Batch usage failed: {(int)res.StatusCode} {body}");
        return body;
    }
}
`;

const CSHARP_WEBHOOK_PROGRAM_CS = `// Program.cs
// SaaS fulfillment v2 webhook - handle subscription lifecycle events (ASP.NET minimal API).
// Docs: https://learn.microsoft.com/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-webhook
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapPost("/webhook", (MarketplaceWebhookEvent evt) =>
{
    // { Id, Action, SubscriptionId, PlanId, Quantity, TimeStamp, Status }
    Console.WriteLine($"Marketplace webhook: {evt.Action} {evt.SubscriptionId}");

    // IMPORTANT: validate the event by calling the GET Operation API before acting on it.
    // Then ACK by PATCHing the operation to Success/Failure.

    switch (evt.Action)
    {
        case "Subscribe":
            // Provision the customer, store subscriptionId -> tenant mapping.
            break;
        case "Unsubscribe":
            // Deprovision / disable access.
            break;
        case "ChangePlan":
            // Update entitlements to the new plan.
            break;
        case "ChangeQuantity":
            // Update seat count.
            break;
        case "Suspend":
            // Payment failed - soft-disable access.
            break;
        case "Reinstate":
            // Payment recovered - restore access.
            break;
        case "Renew":
            // Subscription renewed.
            break;
        default:
            Console.WriteLine($"Unhandled action: {evt.Action}");
            break;
    }

    return Results.Ok();
});

app.Run();

// Example: report metered usage on a schedule (call from your billing job).
// var metering = new BillingStarter.MeteringClient(
//     Environment.GetEnvironmentVariable("AZURE_TENANT_ID")!,
//     Environment.GetEnvironmentVariable("AZURE_CLIENT_ID")!,
//     Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET")!);
// await metering.EmitUsageEventAsync(
//     new BillingStarter.UsageEvent("SUBSCRIPTION_ID", "starter", "api_calls", 0));

public record MarketplaceWebhookEvent(
    string Id,
    string Action,
    string SubscriptionId,
    string PlanId,
    int Quantity,
    string TimeStamp,
    string Status);
`;

const CSHARP_METERING_PROGRAM_CS = `// Program.cs
// Sample entry point that emits a metered usage event via the Marketplace Metering Service.
using BillingStarter;

var tenantId = Environment.GetEnvironmentVariable("AZURE_TENANT_ID")
    ?? throw new InvalidOperationException("AZURE_TENANT_ID not set");
var clientId = Environment.GetEnvironmentVariable("AZURE_CLIENT_ID")
    ?? throw new InvalidOperationException("AZURE_CLIENT_ID not set");
var clientSecret = Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET")
    ?? throw new InvalidOperationException("AZURE_CLIENT_SECRET not set");

var metering = new MeteringClient(tenantId, clientId, clientSecret);

// Replace with your managed-app resourceUsageId / subscription id and real quantity.
await metering.EmitUsageEventAsync(new UsageEvent(
    ResourceId: "REPLACE_RESOURCE_ID",
    PlanId: "starter",
    Dimension: "api_calls",
    Quantity: 0));

Console.WriteLine("Usage event sent.");
`;

/** Add the manifest (package.json / .csproj) for a code starter. */
function addManifest(folder: JSZip, language: BillingLanguage, web: boolean): void {
  if (language === 'csharp') {
    folder.file('BillingStarter.csproj', web ? CSHARP_WEB_CSPROJ : CSHARP_CONSOLE_CSPROJ);
  } else {
    folder.file('package.json', SAAS_PACKAGE_JSON);
  }
}

/** Add the metering implementation file. */
function addMeteringFile(folder: JSZip, language: BillingLanguage): void {
  if (language === 'csharp') {
    folder.file('Metering.cs', CSHARP_METERING_CS);
  } else {
    const src = folder.folder('src');
    if (src) src.file('metering.js', SAAS_METERING_JS);
  }
}

/** Add the SaaS fulfillment webhook file. */
function addWebhookFile(folder: JSZip, language: BillingLanguage): void {
  if (language === 'csharp') {
    folder.file('Program.cs', CSHARP_WEBHOOK_PROGRAM_CS);
  } else {
    const src = folder.folder('src');
    if (src) src.file('webhook.js', SAAS_WEBHOOK_JS);
  }
}

/** Run command hint for INTEGRATION.md, per language. */
function runHint(language: BillingLanguage): string {
  return language === 'csharp' ? '`dotnet run`' : '`node src/webhook.js`';
}

function addSaasMetered(folder: JSZip, language: BillingLanguage): void {
  addMeteringFile(folder, language);
  addWebhookFile(folder, language);
  addManifest(folder, language, true);
  folder.file('pricing.json', SAAS_PRICING_JSON);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# SaaS metered billing integration

1. Register a Microsoft Entra app and add its IDs to \`.env\`.
2. Implement the SaaS fulfillment v2 landing page + resolve/activate flow.
3. Run ${runHint(language)} and register its public URL as the **Connection webhook** in Partner Center.
4. For each metered dimension, emit a usage event with the consumed quantity.
5. Configure plans & dimensions to match \`pricing.json\` in Partner Center.

Key APIs:
- Fulfillment v2: subscription resolve/activate/update.
- Metering Service: \`usageEvent\` / \`batchUsageEvent\`.
`
  );
}

function addSaasSubscription(folder: JSZip, language: BillingLanguage): void {
  addWebhookFile(folder, language);
  addManifest(folder, language, true);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file('pricing.json', SAAS_PRICING_JSON);
  folder.file(
    'INTEGRATION.md',
    `# SaaS subscription (flat / per-user) billing

Microsoft handles recurring billing for flat-rate and per-user plans. Your job:
1. Implement the SaaS fulfillment v2 landing page (resolve the marketplace token).
2. Activate the subscription, then provision the customer.
3. Handle webhook lifecycle events (ChangePlan, ChangeQuantity, Suspend, Reinstate, Unsubscribe).

No metering code is required unless you add a metered dimension - in that case use the
\`saas-metered\` template's metering implementation.
`
  );
}

function addAzureApp(folder: JSZip, language: BillingLanguage): void {
  folder.file(
    'createUiDefinition.sample.json',
    `{
  "$schema": "https://schema.management.azure.com/schemas/0.1.2-preview/CreateUIDefinition.MultiVm.json#",
  "handler": "Microsoft.Azure.CreateUIDef",
  "version": "0.1.2-preview",
  "parameters": { "basics": [], "steps": [], "outputs": {} }
}
`
  );
  folder.file(
    'mainTemplate.sample.json',
    `{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "resources": [],
  "outputs": {}
}
`
  );
  addMeteringFile(folder, language);
  if (language === 'csharp') folder.file('Program.cs', CSHARP_METERING_PROGRAM_CS);
  addManifest(folder, language, false);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# Azure Application (managed app) billing

Package an Azure managed application (\`mainTemplate.json\` + \`createUiDefinition.json\`)
into a .zip and upload it to your plan in Partner Center.

For **metered billing**, the managed app gets a \`resourceUsageId\`; use it as the
\`resourceId\` when calling the Marketplace Metering Service (see the metering files).
`
  );
}

function addAzureVm(folder: JSZip): void {
  folder.file(
    'INTEGRATION.md',
    `# Azure Virtual Machine offer billing

VM offers are billed by Microsoft as **per-core-hour**, **per-core-size**, or **flat
monthly** software fees on top of Azure infra cost - no metering code required.

Checklist:
1. Capture/generalize your VHD and upload to a shared image gallery / storage.
2. Define pricing per VM core/size in Partner Center > Plan > Pricing and availability.
3. (Optional) Offer BYOL (bring-your-own-license) plans for free software pricing.

\`prices.csv\` below is a starting point for your per-size price grid.
`
  );
  folder.file(
    'prices.csv',
    `vmSize,cores,pricePerHourUSD
Standard_D2s_v5,2,0.10
Standard_D4s_v5,4,0.20
Standard_D8s_v5,8,0.40
`
  );
}

function addAzureContainer(folder: JSZip, language: BillingLanguage): void {
  addMeteringFile(folder, language);
  if (language === 'csharp') folder.file('Program.cs', CSHARP_METERING_PROGRAM_CS);
  addManifest(folder, language, false);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# Azure Container / Kubernetes app billing

Container offers (Azure Container, Kubernetes app) commonly use **metered billing**
through the Marketplace Metering Service. Your containerized workload reports usage
via the metering files using the CMA (container marketplace) token / resourceId.

Checklist:
1. Push images to the Azure Container Registry that Partner Center provisions.
2. Define metered dimensions in your plan.
3. Emit usage events from inside the cluster (sidecar or controller).
`
  );
}

function addGeneric(folder: JSZip): void {
  folder.file(
    'INTEGRATION.md',
    `# Marketplace listing - billing notes

This offer type is typically **list-only** (Contact me / Get it now / Free trial) or
billed outside the transact flow. There is no metering integration required.

Use \`plans.json\` to keep your pricing intent documented for your own records, and
review the offer's listing options in Partner Center.
`
  );
}

function addBillingFiles(folder: JSZip, ctx: BillingZipContext): void {
  folder.file('README.md', billingReadme(ctx));
  folder.file('plans.json', plansJson(ctx));

  switch (ctx.billingZipKind) {
    case 'saas-metered':
      addSaasMetered(folder, ctx.language);
      break;
    case 'saas-subscription':
      addSaasSubscription(folder, ctx.language);
      break;
    case 'azure-app':
      addAzureApp(folder, ctx.language);
      break;
    case 'azure-vm':
      addAzureVm(folder);
      break;
    case 'azure-container':
      addAzureContainer(folder, ctx.language);
      break;
    case 'marketplace-generic':
      addGeneric(folder);
      break;
    case 'none':
      addGeneric(folder);
      break;
  }
}

export async function buildBillingZip(ctx: BillingZipContext): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder('billing-starter');
  if (root) addBillingFiles(root, ctx);
  return zip.generateAsync({ type: 'blob' });
}

export interface ProjectAsset {
  filename: string;
  dataUrl: string;
}

export interface ProjectZipContext {
  plan: unknown;
  listingMarkdown: string;
  assets: ProjectAsset[];
  billing?: BillingZipContext;
}

export async function buildProjectZip(ctx: ProjectZipContext): Promise<Blob> {
  const zip = new JSZip();
  zip.file('plan.json', JSON.stringify(ctx.plan, null, 2));
  zip.file('listing.md', ctx.listingMarkdown);

  if (ctx.assets.length) {
    const assetsFolder = zip.folder('assets');
    if (assetsFolder) {
      for (const a of ctx.assets) {
        const base64 = a.dataUrl.split(',')[1];
        if (base64) assetsFolder.file(a.filename, base64, { base64: true });
      }
    }
  }

  if (ctx.billing) {
    const billingFolder = zip.folder('billing');
    if (billingFolder) addBillingFiles(billingFolder, ctx.billing);
  }

  return zip.generateAsync({ type: 'blob' });
}
