import JSZip from 'jszip';
import type { BillingZipKind, BillingLanguage } from '../data/types';
import type { ConfigurePayload, ListingContent } from '../submission/payload';

export interface PlanSummary {
  name: string;
  billingModel: string;
  price: string;
  cadence: string;
  notes: string;
}

export interface BillingZipContext {
  offerName: string;
  offerTypeName: string;
  billingZipKind: BillingZipKind;
  billingModelLabels: string[];
  plans: PlanSummary[];
  /** Implementation language for code files (webhook/metering). Defaults to 'node'. */
  language: BillingLanguage;
}

export function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function languageLabel(language: BillingLanguage): string {
  return language === 'csharp' ? 'C# (.NET 10 / ASP.NET minimal API)' : 'Node.js (Express)';
}

function billingReadme(ctx: BillingZipContext): string {
  return `# Billing starter — ${ctx.offerName || ctx.offerTypeName}

Offer type: **${ctx.offerTypeName}**
Billing template: **${ctx.billingZipKind}**
Implementation language: **${languageLabel(ctx.language)}**

Billing models selected:
${ctx.billingModelLabels.map((b) => `- ${b}`).join('\n') || '- (none selected)'}

## Plans
${
  ctx.plans.length
    ? ctx.plans
        .map(
          (p) =>
            `- **${p.name}** — ${p.billingModel} — ${p.price || 'price TBD'} / ${
              p.cadence || 'cadence TBD'
            }${p.notes ? ` — ${p.notes}` : ''}`
        )
        .join('\n')
    : '- (no plans defined yet)'
}

## What's in this starter
This package gives you a running start on the billing & costing integration your
offer needs in Microsoft commercial marketplace / Partner Center. Review every file,
replace placeholders, and wire it into your own service.

> Generated by the Microsoft Marketplace Offer Wizard. Not an official Microsoft template.
`;
}

function plansJson(ctx: BillingZipContext): string {
  return JSON.stringify(
    {
      offer: ctx.offerName,
      offerType: ctx.offerTypeName,
      billingTemplate: ctx.billingZipKind,
      billingModels: ctx.billingModelLabels,
      plans: ctx.plans
    },
    null,
    2
  );
}

const SAAS_PACKAGE_JSON = `{
  "name": "saas-billing-starter",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node src/webhook.js"
  },
  "dependencies": {
    "@azure/identity": "^4.4.1",
    "express": "^4.19.2"
  }
}
`;

const SAAS_ENV_EXAMPLE = `# Microsoft Entra app registration used to call the Marketplace APIs
AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_SECRET=replace-me

# Local webhook port
PORT=3000
`;

const SAAS_METERING_JS = `// metering.js
// Azure Marketplace Metering Service - emit usage events for metered (pay-as-you-go) dimensions.
// Docs: https://learn.microsoft.com/partner-center/marketplace/marketplace-metering-service-apis
import { ClientSecretCredential } from '@azure/identity';

// Fixed resource/audience for the commercial marketplace metering API.
const MARKETPLACE_SCOPE = '20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default';
const USAGE_EVENT_URL =
  'https://marketplaceapi.microsoft.com/api/usageEvent?api-version=2018-08-31';

const credential = new ClientSecretCredential(
  process.env.AZURE_TENANT_ID,
  process.env.AZURE_CLIENT_ID,
  process.env.AZURE_CLIENT_SECRET
);

async function getToken() {
  const token = await credential.getToken(MARKETPLACE_SCOPE);
  if (!token) throw new Error('Could not acquire a marketplace access token.');
  return token.token;
}

/**
 * Emit a single metered usage event.
 * @param {object} evt
 * @param {string} evt.resourceId  SaaS subscription id (or managed-app resourceUsageId)
 * @param {string} evt.planId      Plan the customer is on
 * @param {string} evt.dimension   Metered dimension id from your plan (e.g. "api_calls")
 * @param {number} evt.quantity    Units consumed since the last event
 */
export async function emitUsageEvent({ resourceId, planId, dimension, quantity }) {
  const accessToken = await getToken();
  const res = await fetch(USAGE_EVENT_URL, {
    method: 'POST',
    headers: {
      Authorization: \`Bearer \${accessToken}\`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      resourceId,
      planId,
      dimension,
      quantity,
      effectiveStartTime: new Date().toISOString()
    })
  });

  if (!res.ok) {
    throw new Error(\`Usage event failed: \${res.status} \${await res.text()}\`);
  }
  return res.json();
}

/**
 * Batch up to 25 usage events in a single call.
 * Docs: .../marketplace-metering-service-apis#metered-billing-batch-usage-event
 */
export async function emitBatchUsage(events) {
  const accessToken = await getToken();
  const res = await fetch(
    'https://marketplaceapi.microsoft.com/api/batchUsageEvent?api-version=2018-08-31',
    {
      method: 'POST',
      headers: {
        Authorization: \`Bearer \${accessToken}\`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ request: events })
    }
  );
  if (!res.ok) {
    throw new Error(\`Batch usage failed: \${res.status} \${await res.text()}\`);
  }
  return res.json();
}
`;

const SAAS_WEBHOOK_JS = `// webhook.js
// SaaS fulfillment v2 webhook - handle subscription lifecycle events.
// Docs: https://learn.microsoft.com/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-webhook
import express from 'express';
import { emitUsageEvent } from './metering.js';

const app = express();
app.use(express.json());

app.post('/webhook', async (req, res) => {
  const event = req.body; // { id, action, subscriptionId, planId, quantity, timeStamp, status }
  console.log('Marketplace webhook:', event.action, event.subscriptionId);

  // IMPORTANT: validate the event by calling the GET Operation API before acting on it.
  // Then ACK by PATCHing the operation to Success/Failure.

  switch (event.action) {
    case 'Subscribe':
      // Provision the customer, store subscriptionId -> tenant mapping.
      break;
    case 'Unsubscribe':
      // Deprovision / disable access.
      break;
    case 'ChangePlan':
      // Update entitlements to the new plan.
      break;
    case 'ChangeQuantity':
      // Update seat count.
      break;
    case 'Suspend':
      // Payment failed - soft-disable access.
      break;
    case 'Reinstate':
      // Payment recovered - restore access.
      break;
    case 'Renew':
      // Subscription renewed.
      break;
    default:
      console.warn('Unhandled action:', event.action);
      break;
  }

  res.sendStatus(200);
});

// Example: report metered usage on a schedule (call from your billing job).
export async function reportDailyUsage(subscriptionId, planId) {
  await emitUsageEvent({
    resourceId: subscriptionId,
    planId,
    dimension: 'api_calls',
    quantity: 0 // replace with real metered quantity
  });
}

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(\`SaaS fulfillment webhook on :\${port}\`));
`;

const SAAS_PRICING_JSON = `{
  "$comment": "Reference shape for plans & metered dimensions. Configure the real values in Partner Center > Plan overview > Pricing and availability.",
  "plans": [
    {
      "planId": "starter",
      "displayName": "Starter",
      "billingTerm": { "value": 1, "type": "Month" },
      "recurrentPrice": { "priceInputOption": "flat", "flatPrice": 0 },
      "dimensions": [
        {
          "id": "api_calls",
          "displayName": "API calls",
          "unitOfMeasure": "calls",
          "pricePerUnit": 0.001,
          "includedQuantity": 10000,
          "overageBilling": true
        }
      ]
    }
  ]
}
`;

// ---------------------------------------------------------------------------
// C# (.NET 10) variants
// ---------------------------------------------------------------------------

const CSHARP_WEB_CSPROJ = `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BillingStarter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
</Project>
`;

const CSHARP_CONSOLE_CSPROJ = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BillingStarter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
  </ItemGroup>
</Project>
`;

const CSHARP_METERING_CS = `// Metering.cs
// Azure Marketplace Metering Service - emit usage events for metered (pay-as-you-go) dimensions.
// Docs: https://learn.microsoft.com/partner-center/marketplace/marketplace-metering-service-apis
using System.Net.Http.Json;
using Azure.Core;
using Azure.Identity;

namespace BillingStarter;

/// <param name="ResourceId">SaaS subscription id (or managed-app resourceUsageId)</param>
/// <param name="PlanId">Plan the customer is on</param>
/// <param name="Dimension">Metered dimension id from your plan (e.g. "api_calls")</param>
/// <param name="Quantity">Units consumed since the last event</param>
public record UsageEvent(string ResourceId, string PlanId, string Dimension, double Quantity);

public class MeteringClient
{
    // Fixed resource/audience for the commercial marketplace metering API.
    private const string MarketplaceScope = "20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default";
    private const string UsageEventUrl =
        "https://marketplaceapi.microsoft.com/api/usageEvent?api-version=2018-08-31";
    private const string BatchUsageUrl =
        "https://marketplaceapi.microsoft.com/api/batchUsageEvent?api-version=2018-08-31";

    private readonly ClientSecretCredential _credential;
    private readonly HttpClient _http = new();

    public MeteringClient(string tenantId, string clientId, string clientSecret)
    {
        _credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
    }

    private async Task<string> GetTokenAsync()
    {
        var token = await _credential.GetTokenAsync(
            new TokenRequestContext(new[] { MarketplaceScope }));
        return token.Token;
    }

    /// <summary>Emit a single metered usage event.</summary>
    public async Task<string> EmitUsageEventAsync(UsageEvent evt)
    {
        var accessToken = await GetTokenAsync();
        using var req = new HttpRequestMessage(HttpMethod.Post, UsageEventUrl);
        req.Headers.Authorization = new("Bearer", accessToken);
        req.Content = JsonContent.Create(new
        {
            resourceId = evt.ResourceId,
            planId = evt.PlanId,
            dimension = evt.Dimension,
            quantity = evt.Quantity,
            effectiveStartTime = DateTime.UtcNow
        });
        var res = await _http.SendAsync(req);
        var body = await res.Content.ReadAsStringAsync();
        if (!res.IsSuccessStatusCode)
            throw new InvalidOperationException($"Usage event failed: {(int)res.StatusCode} {body}");
        return body;
    }

    /// <summary>Batch up to 25 usage events in a single call.</summary>
    public async Task<string> EmitBatchUsageAsync(IEnumerable<UsageEvent> events)
    {
        var accessToken = await GetTokenAsync();
        using var req = new HttpRequestMessage(HttpMethod.Post, BatchUsageUrl);
        req.Headers.Authorization = new("Bearer", accessToken);
        req.Content = JsonContent.Create(new
        {
            request = events.Select(e => new
            {
                resourceId = e.ResourceId,
                planId = e.PlanId,
                dimension = e.Dimension,
                quantity = e.Quantity,
                effectiveStartTime = DateTime.UtcNow
            })
        });
        var res = await _http.SendAsync(req);
        var body = await res.Content.ReadAsStringAsync();
        if (!res.IsSuccessStatusCode)
            throw new InvalidOperationException($"Batch usage failed: {(int)res.StatusCode} {body}");
        return body;
    }
}
`;

const CSHARP_WEBHOOK_PROGRAM_CS = `// Program.cs
// SaaS fulfillment v2 webhook - handle subscription lifecycle events (ASP.NET minimal API).
// Docs: https://learn.microsoft.com/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-webhook
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapPost("/webhook", (MarketplaceWebhookEvent evt) =>
{
    // { Id, Action, SubscriptionId, PlanId, Quantity, TimeStamp, Status }
    Console.WriteLine($"Marketplace webhook: {evt.Action} {evt.SubscriptionId}");

    // IMPORTANT: validate the event by calling the GET Operation API before acting on it.
    // Then ACK by PATCHing the operation to Success/Failure.

    switch (evt.Action)
    {
        case "Subscribe":
            // Provision the customer, store subscriptionId -> tenant mapping.
            break;
        case "Unsubscribe":
            // Deprovision / disable access.
            break;
        case "ChangePlan":
            // Update entitlements to the new plan.
            break;
        case "ChangeQuantity":
            // Update seat count.
            break;
        case "Suspend":
            // Payment failed - soft-disable access.
            break;
        case "Reinstate":
            // Payment recovered - restore access.
            break;
        case "Renew":
            // Subscription renewed.
            break;
        default:
            Console.WriteLine($"Unhandled action: {evt.Action}");
            break;
    }

    return Results.Ok();
});

app.Run();

// Example: report metered usage on a schedule (call from your billing job).
// var metering = new BillingStarter.MeteringClient(
//     Environment.GetEnvironmentVariable("AZURE_TENANT_ID")!,
//     Environment.GetEnvironmentVariable("AZURE_CLIENT_ID")!,
//     Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET")!);
// await metering.EmitUsageEventAsync(
//     new BillingStarter.UsageEvent("SUBSCRIPTION_ID", "starter", "api_calls", 0));

public record MarketplaceWebhookEvent(
    string Id,
    string Action,
    string SubscriptionId,
    string PlanId,
    int Quantity,
    string TimeStamp,
    string Status);
`;

const CSHARP_METERING_PROGRAM_CS = `// Program.cs
// Sample entry point that emits a metered usage event via the Marketplace Metering Service.
using BillingStarter;

var tenantId = Environment.GetEnvironmentVariable("AZURE_TENANT_ID")
    ?? throw new InvalidOperationException("AZURE_TENANT_ID not set");
var clientId = Environment.GetEnvironmentVariable("AZURE_CLIENT_ID")
    ?? throw new InvalidOperationException("AZURE_CLIENT_ID not set");
var clientSecret = Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET")
    ?? throw new InvalidOperationException("AZURE_CLIENT_SECRET not set");

var metering = new MeteringClient(tenantId, clientId, clientSecret);

// Replace with your managed-app resourceUsageId / subscription id and real quantity.
await metering.EmitUsageEventAsync(new UsageEvent(
    ResourceId: "REPLACE_RESOURCE_ID",
    PlanId: "starter",
    Dimension: "api_calls",
    Quantity: 0));

Console.WriteLine("Usage event sent.");
`;

/** Add the manifest (package.json / .csproj) for a code starter. */
function addManifest(folder: JSZip, language: BillingLanguage, web: boolean): void {
  if (language === 'csharp') {
    folder.file('BillingStarter.csproj', web ? CSHARP_WEB_CSPROJ : CSHARP_CONSOLE_CSPROJ);
  } else {
    folder.file('package.json', SAAS_PACKAGE_JSON);
  }
}

/** Add the metering implementation file. */
function addMeteringFile(folder: JSZip, language: BillingLanguage): void {
  if (language === 'csharp') {
    folder.file('Metering.cs', CSHARP_METERING_CS);
  } else {
    const src = folder.folder('src');
    if (src) src.file('metering.js', SAAS_METERING_JS);
  }
}

/** Add the SaaS fulfillment webhook file. */
function addWebhookFile(folder: JSZip, language: BillingLanguage): void {
  if (language === 'csharp') {
    folder.file('Program.cs', CSHARP_WEBHOOK_PROGRAM_CS);
  } else {
    const src = folder.folder('src');
    if (src) src.file('webhook.js', SAAS_WEBHOOK_JS);
  }
}

/** Run command hint for INTEGRATION.md, per language. */
function runHint(language: BillingLanguage): string {
  return language === 'csharp' ? '`dotnet run`' : '`node src/webhook.js`';
}

function addSaasMetered(folder: JSZip, language: BillingLanguage): void {
  addMeteringFile(folder, language);
  addWebhookFile(folder, language);
  addManifest(folder, language, true);
  folder.file('pricing.json', SAAS_PRICING_JSON);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# SaaS metered billing integration

1. Register a Microsoft Entra app and add its IDs to \`.env\`.
2. Implement the SaaS fulfillment v2 landing page + resolve/activate flow.
3. Run ${runHint(language)} and register its public URL as the **Connection webhook** in Partner Center.
4. For each metered dimension, emit a usage event with the consumed quantity.
5. Configure plans & dimensions to match \`pricing.json\` in Partner Center.

Key APIs:
- Fulfillment v2: subscription resolve/activate/update.
- Metering Service: \`usageEvent\` / \`batchUsageEvent\`.
`
  );
}

function addSaasSubscription(folder: JSZip, language: BillingLanguage): void {
  addWebhookFile(folder, language);
  addManifest(folder, language, true);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file('pricing.json', SAAS_PRICING_JSON);
  folder.file(
    'INTEGRATION.md',
    `# SaaS subscription (flat / per-user) billing

Microsoft handles recurring billing for flat-rate and per-user plans. Your job:
1. Implement the SaaS fulfillment v2 landing page (resolve the marketplace token).
2. Activate the subscription, then provision the customer.
3. Handle webhook lifecycle events (ChangePlan, ChangeQuantity, Suspend, Reinstate, Unsubscribe).

No metering code is required unless you add a metered dimension - in that case use the
\`saas-metered\` template's metering implementation.
`
  );
}

function addAzureApp(folder: JSZip, language: BillingLanguage): void {
  folder.file(
    'createUiDefinition.sample.json',
    `{
  "$schema": "https://schema.management.azure.com/schemas/0.1.2-preview/CreateUIDefinition.MultiVm.json#",
  "handler": "Microsoft.Azure.CreateUIDef",
  "version": "0.1.2-preview",
  "parameters": { "basics": [], "steps": [], "outputs": {} }
}
`
  );
  folder.file(
    'mainTemplate.sample.json',
    `{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "resources": [],
  "outputs": {}
}
`
  );
  addMeteringFile(folder, language);
  if (language === 'csharp') folder.file('Program.cs', CSHARP_METERING_PROGRAM_CS);
  addManifest(folder, language, false);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# Azure Application (managed app) billing

Package an Azure managed application (\`mainTemplate.json\` + \`createUiDefinition.json\`)
into a .zip and upload it to your plan in Partner Center.

For **metered billing**, the managed app gets a \`resourceUsageId\`; use it as the
\`resourceId\` when calling the Marketplace Metering Service (see the metering files).
`
  );
}

function addAzureVm(folder: JSZip): void {
  folder.file(
    'INTEGRATION.md',
    `# Azure Virtual Machine offer billing

VM offers are billed by Microsoft as **per-core-hour**, **per-core-size**, or **flat
monthly** software fees on top of Azure infra cost - no metering code required.

Checklist:
1. Capture/generalize your VHD and upload to a shared image gallery / storage.
2. Define pricing per VM core/size in Partner Center > Plan > Pricing and availability.
3. (Optional) Offer BYOL (bring-your-own-license) plans for free software pricing.

\`prices.csv\` below is a starting point for your per-size price grid.
`
  );
  folder.file(
    'prices.csv',
    `vmSize,cores,pricePerHourUSD
Standard_D2s_v5,2,0.10
Standard_D4s_v5,4,0.20
Standard_D8s_v5,8,0.40
`
  );
}

function addAzureContainer(folder: JSZip, language: BillingLanguage): void {
  addMeteringFile(folder, language);
  if (language === 'csharp') folder.file('Program.cs', CSHARP_METERING_PROGRAM_CS);
  addManifest(folder, language, false);
  folder.file('.env.example', SAAS_ENV_EXAMPLE);
  folder.file(
    'INTEGRATION.md',
    `# Azure Container / Kubernetes app billing

Container offers (Azure Container, Kubernetes app) commonly use **metered billing**
through the Marketplace Metering Service. Your containerized workload reports usage
via the metering files using the CMA (container marketplace) token / resourceId.

Checklist:
1. Push images to the Azure Container Registry that Partner Center provisions.
2. Define metered dimensions in your plan.
3. Emit usage events from inside the cluster (sidecar or controller).
`
  );
}

function addGeneric(folder: JSZip): void {
  folder.file(
    'INTEGRATION.md',
    `# Marketplace listing - billing notes

This offer type is typically **list-only** (Contact me / Get it now / Free trial) or
billed outside the transact flow. There is no metering integration required.

Use \`plans.json\` to keep your pricing intent documented for your own records, and
review the offer's listing options in Partner Center.
`
  );
}

function addBillingFiles(folder: JSZip, ctx: BillingZipContext): void {
  folder.file('README.md', billingReadme(ctx));
  folder.file('plans.json', plansJson(ctx));

  switch (ctx.billingZipKind) {
    case 'saas-metered':
      addSaasMetered(folder, ctx.language);
      break;
    case 'saas-subscription':
      addSaasSubscription(folder, ctx.language);
      break;
    case 'azure-app':
      addAzureApp(folder, ctx.language);
      break;
    case 'azure-vm':
      addAzureVm(folder);
      break;
    case 'azure-container':
      addAzureContainer(folder, ctx.language);
      break;
    case 'marketplace-generic':
      addGeneric(folder);
      break;
    case 'none':
      addGeneric(folder);
      break;
  }
}

export async function buildBillingZip(ctx: BillingZipContext): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder('billing-starter');
  if (root) addBillingFiles(root, ctx);
  return zip.generateAsync({ type: 'blob' });
}

export interface ProjectAsset {
  filename: string;
  dataUrl: string;
}

export interface ProjectZipContext {
  plan: unknown;
  listingMarkdown: string;
  assets: ProjectAsset[];
  billing?: BillingZipContext;
}

export async function buildProjectZip(ctx: ProjectZipContext): Promise<Blob> {
  const zip = new JSZip();
  zip.file('plan.json', JSON.stringify(ctx.plan, null, 2));
  zip.file('listing.md', ctx.listingMarkdown);

  if (ctx.assets.length) {
    const assetsFolder = zip.folder('assets');
    if (assetsFolder) {
      for (const a of ctx.assets) {
        const base64 = a.dataUrl.split(',')[1];
        if (base64) assetsFolder.file(a.filename, base64, { base64: true });
      }
    }
  }

  if (ctx.billing) {
    const billingFolder = zip.folder('billing');
    if (billingFolder) addBillingFiles(billingFolder, ctx.billing);
  }

  return zip.generateAsync({ type: 'blob' });
}

// ---------------------------------------------------------------------------
// Partner Center submission bundle (Product Ingestion API)
// ---------------------------------------------------------------------------

export interface SubmissionZipContext {
  offerName: string;
  offerTypeName: string;
  productIngestionType: string;
  transactable: boolean;
  language: BillingLanguage;
  configurePayload: ConfigurePayload;
  listingContent: ListingContent;
  prerequisites: string[];
}

const SUBMISSION_ENV_EXAMPLE = `# Microsoft Entra service principal used to call the Product Ingestion API.
# Create the app registration in YOUR (the partner's) tenant, add a client secret,
# then in Partner Center go to: Account settings > User management >
# "Azure AD applications" > add this app with the **Manager** role.
AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
AZURE_CLIENT_SECRET=replace-me
`;

const SUBMISSION_PS1 = `#requires -Version 7
<#
.SYNOPSIS
  Submit configure.json to the Microsoft Partner Center Product Ingestion API.
.DESCRIPTION
  Acquires an access token with a Microsoft Entra service principal (client
  credentials) and POSTs configure.json, which creates a DRAFT product plus plan
  skeletons. Listing copy and pricing are intentionally NOT in this payload -
  see MAPPING.md for how to apply listing-content.json after the draft exists.
.PARAMETER EnvFile
  Path to a .env file holding AZURE_TENANT_ID / AZURE_CLIENT_ID / AZURE_CLIENT_SECRET.
.PARAMETER Target
  draft (default), preview, or live. preview and live add a submission resource.
  live requires the offer to have been published to preview first.
.PARAMETER ExportResourceTree
  After success, GET the product resource-tree and save it to resource-tree.json.
.EXAMPLE
  pwsh ./submit.ps1
.EXAMPLE
  pwsh ./submit.ps1 -Target preview -ExportResourceTree
#>
param(
  [string]$EnvFile = '.env',
  [ValidateSet('draft', 'preview', 'live')][string]$Target = 'draft',
  [switch]$ExportResourceTree
)

$ErrorActionPreference = 'Stop'
$apiVersion = '2022-03-01-preview2'
$base = 'https://graph.microsoft.com/rp/product-ingestion'
$schemaBase = 'https://schema.mp.microsoft.com/schema'

function Import-EnvFile([string]$path) {
  if (-not (Test-Path $path)) {
    throw "Env file not found: $path. Copy .env.example to .env and fill in your service principal."
  }
  Get-Content $path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith('#')) { return }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { return }
    $name = $line.Substring(0, $idx).Trim()
    $value = $line.Substring($idx + 1).Trim()
    Set-Item -Path "Env:$name" -Value $value
  }
}

Import-EnvFile $EnvFile
$tenant = $env:AZURE_TENANT_ID
$clientId = $env:AZURE_CLIENT_ID
$clientSecret = $env:AZURE_CLIENT_SECRET
if (-not $tenant -or -not $clientId -or -not $clientSecret) {
  throw 'AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_SECRET must all be set.'
}

Write-Host 'Acquiring access token...'
$tokenResponse = Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/$tenant/oauth2/v2.0/token" -Body @{
  client_id     = $clientId
  scope         = 'https://graph.microsoft.com/.default'
  client_secret = $clientSecret
  grant_type    = 'client_credentials'
}
$headers = @{ Authorization = "Bearer $($tokenResponse.access_token)" }

$configurePath = Join-Path $PSScriptRoot 'configure.json'
$configureBody = Get-Content -Raw -Path $configurePath
$configure = $configureBody | ConvertFrom-Json
$productExternalId = ($configure.resources |
  Where-Object { $_.type -in @('softwareAsAService', 'azureVirtualMachine', 'azureContainer') } |
  Select-Object -First 1).identity.externalID

Write-Host 'Submitting configure payload (creates a draft skeleton)...'
$job = Invoke-RestMethod -Method Post -Uri "$base/configure?\`$version=$apiVersion" -Headers $headers -ContentType 'application/json' -Body $configureBody
while ($job.jobStatus -eq 'running') {
  Start-Sleep -Seconds 5
  $job = Invoke-RestMethod -Method Get -Uri "$base/configure/$($job.jobId)?\`$version=$apiVersion" -Headers $headers
  Write-Host "  job $($job.jobId): $($job.jobStatus) / $($job.jobResult)"
}
if ($job.jobResult -ne 'succeeded') {
  Write-Error "Configure job failed: $($job | ConvertTo-Json -Depth 10)"
  exit 1
}
Write-Host 'Draft created.' -ForegroundColor Green

$product = Invoke-RestMethod -Method Get -Uri "$base/product?externalId=$productExternalId&\`$version=$apiVersion" -Headers $headers
$productId = $product.id
Write-Host "Product durable id: $productId"

if ($ExportResourceTree) {
  Write-Host 'Exporting resource tree...'
  $tree = Invoke-RestMethod -Method Get -Uri "$base/resource-tree/$productId?\`$version=$apiVersion" -Headers $headers
  $tree | ConvertTo-Json -Depth 25 | Out-File -FilePath (Join-Path $PSScriptRoot 'resource-tree.json') -Encoding utf8
  Write-Host 'Saved resource-tree.json - map listing-content.json onto it, then re-submit the listing resource.'
}

if ($Target -ne 'draft') {
  Write-Host "Publishing to $Target..."
  $submission = @{
    '$schema' = "$schemaBase/submission/$apiVersion"
    product   = $productId
    target    = @{ targetType = $Target }
  }
  $publishBody = @{
    '$schema'   = "$schemaBase/configure/$apiVersion"
    'resources' = @($submission)
  } | ConvertTo-Json -Depth 10
  $pub = Invoke-RestMethod -Method Post -Uri "$base/configure?\`$version=$apiVersion" -Headers $headers -ContentType 'application/json' -Body $publishBody
  while ($pub.jobStatus -eq 'running') {
    Start-Sleep -Seconds 10
    $pub = Invoke-RestMethod -Method Get -Uri "$base/configure/$($pub.jobId)?\`$version=$apiVersion" -Headers $headers
    Write-Host "  publish: $($pub.jobStatus) / $($pub.jobResult)"
  }
  Write-Host "Publish result: $($pub.jobResult)"
}
`;

const SUBMISSION_PACKAGE_JSON = `{
  "name": "marketplace-submit",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "engines": {
    "node": ">=18"
  },
  "scripts": {
    "submit": "node submit.mjs"
  }
}
`;

const SUBMISSION_MJS = `// submit.mjs
// Submit configure.json to the Microsoft Partner Center Product Ingestion API.
// Requires Node.js 18+ (uses the global fetch API). No npm dependencies.
//
// Usage:
//   node submit.mjs
//   node submit.mjs --target preview --export-resource-tree
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const apiVersion = '2022-03-01-preview2';
const base = 'https://graph.microsoft.com/rp/product-ingestion';
const schemaBase = 'https://schema.mp.microsoft.com/schema';

function loadEnv(path) {
  try {
    for (const raw of readFileSync(path, 'utf8').split(/\\r?\\n/)) {
      const line = raw.trim();
      if (!line || line.startsWith('#')) continue;
      const i = line.indexOf('=');
      if (i < 1) continue;
      const key = line.slice(0, i).trim();
      if (!process.env[key]) process.env[key] = line.slice(i + 1).trim();
    }
  } catch {
    // .env is optional when the variables are already exported.
  }
}

const argv = process.argv.slice(2);
const argValue = (name, fallback) => {
  const i = argv.indexOf(name);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : fallback;
};
const target = argValue('--target', 'draft');
const exportTree = argv.includes('--export-resource-tree');

loadEnv(join(here, argValue('--env', '.env')));
const tenant = process.env.AZURE_TENANT_ID;
const clientId = process.env.AZURE_CLIENT_ID;
const clientSecret = process.env.AZURE_CLIENT_SECRET;
if (!tenant || !clientId || !clientSecret) {
  throw new Error('AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_SECRET must all be set.');
}

async function getToken() {
  const res = await fetch(\\\`https://login.microsoftonline.com/\\\${tenant}/oauth2/v2.0/token\\\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: clientId,
      scope: 'https://graph.microsoft.com/.default',
      client_secret: clientSecret,
      grant_type: 'client_credentials'
    })
  });
  if (!res.ok) throw new Error(\\\`Token request failed: \\\${res.status} \\\${await res.text()}\\\`);
  return (await res.json()).access_token;
}

const token = await getToken();
const authHeaders = { Authorization: \\\`Bearer \\\${token}\\\` };
const qv = \\\`?$version=\\\${apiVersion}\\\`;

async function api(method, path, body) {
  const res = await fetch(\\\`\\\${base}\\\${path}\\\`, {
    method,
    headers: { ...authHeaders, ...(body ? { 'Content-Type': 'application/json' } : {}) },
    body: body ? (typeof body === 'string' ? body : JSON.stringify(body)) : undefined
  });
  if (!res.ok) throw new Error(\\\`\\\${method} \\\${path} failed: \\\${res.status} \\\${await res.text()}\\\`);
  return res.json();
}

const configureBody = readFileSync(join(here, 'configure.json'), 'utf8');
const configure = JSON.parse(configureBody);
const productResource = configure.resources.find((r) =>
  ['softwareAsAService', 'azureVirtualMachine', 'azureContainer'].includes(r.type)
);
const productExternalId = productResource?.identity?.externalID;

console.log('Submitting configure payload (creates a draft skeleton)...');
let job = await api('POST', \\\`/configure\\\${qv}\\\`, configureBody);
while (job.jobStatus === 'running') {
  await new Promise((r) => setTimeout(r, 5000));
  job = await api('GET', \\\`/configure/\\\${job.jobId}\\\${qv}\\\`);
  console.log(\\\`  job \\\${job.jobId}: \\\${job.jobStatus} / \\\${job.jobResult}\\\`);
}
if (job.jobResult !== 'succeeded') {
  console.error('Configure job failed:', JSON.stringify(job, null, 2));
  process.exit(1);
}
console.log('Draft created.');

const product = await api('GET', \\\`/product?externalId=\\\${productExternalId}&$version=\\\${apiVersion}\\\`);
const productId = product.id;
console.log('Product durable id:', productId);

if (exportTree) {
  const tree = await api('GET', \\\`/resource-tree/\\\${productId}\\\${qv}\\\`);
  writeFileSync(join(here, 'resource-tree.json'), JSON.stringify(tree, null, 2));
  console.log('Saved resource-tree.json - map listing-content.json onto it, then re-submit the listing resource.');
}

if (target !== 'draft') {
  console.log(\\\`Publishing to \\\${target}...\\\`);
  const payload = {
    '$schema': \\\`\\\${schemaBase}/configure/\\\${apiVersion}\\\`,
    resources: [
      {
        '$schema': \\\`\\\${schemaBase}/submission/\\\${apiVersion}\\\`,
        product: productId,
        target: { targetType: target }
      }
    ]
  };
  let pub = await api('POST', \\\`/configure\\\${qv}\\\`, payload);
  while (pub.jobStatus === 'running') {
    await new Promise((r) => setTimeout(r, 10000));
    pub = await api('GET', \\\`/configure/\\\${pub.jobId}\\\${qv}\\\`);
    console.log(\\\`  publish: \\\${pub.jobStatus} / \\\${pub.jobResult}\\\`);
  }
  console.log('Publish result:', pub.jobResult);
}
`;

const SUBMISSION_CSPROJ = `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MarketplaceSubmit</RootNamespace>
  </PropertyGroup>

</Project>
`;

const SUBMISSION_PROGRAM_CS = `// Program.cs
// Submit configure.json to the Microsoft Partner Center Product Ingestion API.
// .NET 10 console app. No external NuGet packages required.
//
// Usage:
//   dotnet run -- --target draft
//   dotnet run -- --target preview --export-resource-tree
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

const string apiVersion = "2022-03-01-preview2";
const string baseUrl = "https://graph.microsoft.com/rp/product-ingestion";
const string schemaBase = "https://schema.mp.microsoft.com/schema";
var qv = "?$version=" + apiVersion;

var envFile = GetArg(args, "--env") ?? ".env";
var target = GetArg(args, "--target") ?? "draft";
var exportTree = args.Contains("--export-resource-tree");

LoadEnv(envFile);
var tenant = Environment.GetEnvironmentVariable("AZURE_TENANT_ID");
var clientId = Environment.GetEnvironmentVariable("AZURE_CLIENT_ID");
var clientSecret = Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET");
if (string.IsNullOrWhiteSpace(tenant) || string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret))
    throw new InvalidOperationException("AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_SECRET must all be set.");

using var http = new HttpClient();
var token = await GetTokenAsync();
http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

var configurePath = File.Exists("configure.json")
    ? "configure.json"
    : Path.Combine(AppContext.BaseDirectory, "configure.json");
var configureBody = await File.ReadAllTextAsync(configurePath);
using var configureDoc = JsonDocument.Parse(configureBody);
string? productExternalId = null;
foreach (var r in configureDoc.RootElement.GetProperty("resources").EnumerateArray())
{
    if (r.TryGetProperty("type", out var t) &&
        t.GetString() is "softwareAsAService" or "azureVirtualMachine" or "azureContainer")
    {
        productExternalId = r.GetProperty("identity").GetProperty("externalID").GetString();
        break;
    }
}

Console.WriteLine("Submitting configure payload (creates a draft skeleton)...");
var job = await PostAsync("/configure" + qv, configureBody);
while (job.GetProperty("jobStatus").GetString() == "running")
{
    await Task.Delay(5000);
    job = await GetAsync("/configure/" + job.GetProperty("jobId").GetString() + qv);
    Console.WriteLine("  job: " + job.GetProperty("jobStatus").GetString() + " / " + JobResult(job));
}
if (JobResult(job) != "succeeded")
{
    Console.Error.WriteLine("Configure job failed: " + job.ToString());
    Environment.Exit(1);
}
Console.WriteLine("Draft created.");

var product = await GetAsync("/product?externalId=" + productExternalId + "&$version=" + apiVersion);
var productId = product.GetProperty("id").GetString();
Console.WriteLine("Product durable id: " + productId);

if (exportTree)
{
    var tree = await GetAsync("/resource-tree/" + productId + qv);
    await File.WriteAllTextAsync("resource-tree.json", tree.ToString());
    Console.WriteLine("Saved resource-tree.json - map listing-content.json onto it, then re-submit the listing resource.");
}

if (target != "draft")
{
    Console.WriteLine("Publishing to " + target + "...");
    var publishBody =
        "{\\"$schema\\":\\"" + schemaBase + "/configure/" + apiVersion + "\\"," +
        "\\"resources\\":[{\\"$schema\\":\\"" + schemaBase + "/submission/" + apiVersion + "\\"," +
        "\\"product\\":\\"" + productId + "\\",\\"target\\":{\\"targetType\\":\\"" + target + "\\"}}]}";
    var pub = await PostAsync("/configure" + qv, publishBody);
    while (pub.GetProperty("jobStatus").GetString() == "running")
    {
        await Task.Delay(10000);
        pub = await GetAsync("/configure/" + pub.GetProperty("jobId").GetString() + qv);
        Console.WriteLine("  publish: " + pub.GetProperty("jobStatus").GetString() + " / " + JobResult(pub));
    }
    Console.WriteLine("Publish result: " + JobResult(pub));
}

static string JobResult(JsonElement e) =>
    e.TryGetProperty("jobResult", out var jr) ? jr.GetString() ?? "" : "";

async Task<JsonElement> PostAsync(string path, string body)
{
    using var content = new StringContent(body, Encoding.UTF8, "application/json");
    var res = await http.PostAsync(baseUrl + path, content);
    var text = await res.Content.ReadAsStringAsync();
    if (!res.IsSuccessStatusCode)
        throw new HttpRequestException("POST " + path + " failed: " + (int)res.StatusCode + " " + text);
    return JsonDocument.Parse(text).RootElement.Clone();
}

async Task<JsonElement> GetAsync(string path)
{
    var res = await http.GetAsync(baseUrl + path);
    var text = await res.Content.ReadAsStringAsync();
    if (!res.IsSuccessStatusCode)
        throw new HttpRequestException("GET " + path + " failed: " + (int)res.StatusCode + " " + text);
    return JsonDocument.Parse(text).RootElement.Clone();
}

async Task<string> GetTokenAsync()
{
    using var form = new FormUrlEncodedContent(new Dictionary<string, string>
    {
        ["client_id"] = clientId!,
        ["scope"] = "https://graph.microsoft.com/.default",
        ["client_secret"] = clientSecret!,
        ["grant_type"] = "client_credentials"
    });
    using var tokenClient = new HttpClient();
    var res = await tokenClient.PostAsync(
        "https://login.microsoftonline.com/" + tenant + "/oauth2/v2.0/token", form);
    var text = await res.Content.ReadAsStringAsync();
    if (!res.IsSuccessStatusCode)
        throw new HttpRequestException("Token request failed: " + text);
    using var doc = JsonDocument.Parse(text);
    return doc.RootElement.GetProperty("access_token").GetString()!;
}

static string? GetArg(string[] argv, string name)
{
    var i = Array.IndexOf(argv, name);
    return i >= 0 && i + 1 < argv.Length ? argv[i + 1] : null;
}

static void LoadEnv(string path)
{
    if (!File.Exists(path)) return;
    foreach (var raw in File.ReadAllLines(path))
    {
        var line = raw.Trim();
        if (line.Length == 0 || line.StartsWith('#')) continue;
        var idx = line.IndexOf('=');
        if (idx < 1) continue;
        var key = line[..idx].Trim();
        var value = line[(idx + 1)..].Trim();
        if (Environment.GetEnvironmentVariable(key) is null)
            Environment.SetEnvironmentVariable(key, value);
    }
}
`;

const SUBMISSION_WORKFLOW_YML = `name: Submit marketplace offer

# Secretless submission using Microsoft Entra Workload Identity Federation (OIDC).
# Configure a federated credential on your app registration for this repository,
# then set repository variables AZURE_TENANT_ID and AZURE_CLIENT_ID.
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'draft | preview | live'
        required: true
        default: 'draft'

permissions:
  id-token: write
  contents: read

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC - no stored secret)
        uses: azure/login@v2
        with:
          client-id: \\\${{ vars.AZURE_CLIENT_ID }}
          tenant-id: \\\${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Submit configure payload
        shell: pwsh
        run: |
          $apiVersion = '2022-03-01-preview2'
          $base = 'https://graph.microsoft.com/rp/product-ingestion'
          $token = az account get-access-token --resource https://graph.microsoft.com --query accessToken -o tsv
          $headers = @{ Authorization = "Bearer $token" }
          $body = Get-Content -Raw configure.json
          $job = Invoke-RestMethod -Method Post -Uri "$base/configure?\\\`$version=$apiVersion" -Headers $headers -ContentType 'application/json' -Body $body
          while ($job.jobStatus -eq 'running') {
            Start-Sleep -Seconds 5
            $job = Invoke-RestMethod -Method Get -Uri "$base/configure/$($job.jobId)?\\\`$version=$apiVersion" -Headers $headers
            Write-Host "$($job.jobStatus) / $($job.jobResult)"
          }
          if ($job.jobResult -ne 'succeeded') { throw "Configure failed: $($job | ConvertTo-Json -Depth 10)" }
          Write-Host 'Draft created.'
`;

function submissionRunInstructions(ctx: SubmissionZipContext): string {
  if (ctx.language === 'csharp') {
    return [
      '```bash',
      '# .NET 10 SDK required',
      'cd Submit',
      'cp ../.env.example ../.env   # then edit ../.env',
      'dotnet run -- --target draft',
      '```'
    ].join('\\n');
  }
  return [
    '```bash',
    '# Node.js 18+ required (no npm install needed)',
    'cp .env.example .env   # then edit .env',
    'node submit.mjs --target draft',
    '```'
  ].join('\\n');
}

function submissionReadme(ctx: SubmissionZipContext): string {
  const prereqs = ctx.prerequisites.length
    ? ctx.prerequisites.map((p) => `- ${p}`).join('\\n')
    : '- A live Partner Center account enrolled in the commercial marketplace program.';
  return `# Submit "${ctx.offerName}" to Partner Center

This bundle was generated by the Marketplace Offer Wizard. It submits your
**${ctx.offerTypeName}** offer to the Microsoft Partner Center **Product Ingestion API**
using **your own** Microsoft Entra service principal. Nothing here calls a third-party
backend and no credentials ever leave your machine (or your CI runner).

## What gets submitted

The wizard cannot guess every field of the large, frequently-changing listing schema,
so this bundle is intentionally **two-tier**:

1. **\`configure.json\`** - a guaranteed-valid \`configure\` payload that creates a **draft**:
   the product${ctx.productIngestionType === 'softwareAsAService' ? ', the commercial-marketplace-setup,' : ''} and your plan skeleton(s).
   The submit script POSTs this as-is.
2. **\`listing-content.json\`** - your listing copy, search keywords and links. This is a
   neutral sidecar you apply **after** the draft exists - see \`MAPPING.md\`.

> The \`configure\` API is atomic: one invalid property fails the whole job. Keeping listing
> copy out of the automated payload means the draft always succeeds; you then layer the
> listing on with full visibility via \`-ExportResourceTree\`.

## Prerequisites

${prereqs}
- An Entra app registration (service principal) in your tenant with a client secret.
- That service principal added in **Partner Center > Account settings > User management >
  Azure AD applications** with the **Manager** role.
- PowerShell 7+ (for \`submit.ps1\`)${ctx.language === 'csharp' ? ', plus the **.NET 10 SDK** for the C# variant.' : ', or **Node.js 18+** for \`submit.mjs\`.'}

## Run it

Fill in your service principal, then create the draft:

${submissionRunInstructions(ctx)}

Or use the always-available cross-platform PowerShell script:

\`\`\`bash
cp .env.example .env   # then edit .env
pwsh ./submit.ps1 -Target draft
\`\`\`

### Publish to preview / live

\`\`\`bash
pwsh ./submit.ps1 -Target preview -ExportResourceTree
# review the preview offer in Partner Center, then:
pwsh ./submit.ps1 -Target live
\`\`\`

\`-Target preview\` and \`-Target live\` add a \`submission\` resource that requests publishing.
\`live\` requires the offer to have reached **preview** first.

## CI (optional, secretless)

\`.github/workflows/submit.yml\` submits the draft from GitHub Actions using **Workload
Identity Federation (OIDC)** - configure a federated credential on the app registration
and set repository variables \`AZURE_TENANT_ID\` and \`AZURE_CLIENT_ID\`. No client secret
is stored anywhere.

## Files

| File | Purpose |
| --- | --- |
| \`configure.json\` | The Product Ingestion \`configure\` payload (draft skeleton). |
| \`listing-content.json\` | Listing copy + links to apply after the draft exists. |
| \`submit.ps1\` | PowerShell submit/poll/publish script (cross-platform). |
| ${ctx.language === 'csharp' ? '`Submit/`' : '`submit.mjs`'} | ${ctx.language === 'csharp' ? '.NET 10 console variant.' : 'Node.js variant.'} |
| \`.env.example\` | Template for your service principal credentials. |
| \`MAPPING.md\` | How to apply \`listing-content.json\` onto the live listing schema. |
| \`.github/workflows/submit.yml\` | Optional secretless CI submission (OIDC). |
`;
}

function submissionMapping(ctx: SubmissionZipContext): string {
  return `# Applying your listing content

\`configure.json\` deliberately omits the marketplace **listing** (descriptions, search
keywords, links, images) and **pricing schedule** because those schemas are large and
change often. This file explains how to layer \`listing-content.json\` onto your draft.

## 1. Create the draft

\`\`\`bash
pwsh ./submit.ps1 -Target draft -ExportResourceTree
\`\`\`

\`-ExportResourceTree\` writes \`resource-tree.json\` - the full, current resource graph for
your product, including the exact \`listing\` resource schema and IDs Partner Center expects
for **${ctx.offerTypeName}**.

## 2. Map listing-content.json onto the listing resource

Open \`resource-tree.json\` and find the resource whose \`$schema\` ends in \`/listing/...\`.
Copy these values from \`listing-content.json\` into it:

| listing-content.json | Listing resource field |
| --- | --- |
| \`title\` | \`title\` |
| \`searchResultSummary\` | \`searchResultSummary\` |
| \`shortDescription\` | \`shortDescription\` |
| \`description\` | \`description\` (HTML allowed) |
| \`keywords\` | \`searchKeywords\` |
| \`gettingStartedInstructions\` | \`gettingStartedInstructions\` |
| \`privacyPolicyLink\` | \`privacyPolicyLink\` |
| \`supportLink\` (or contact) | \`supportContact\` / \`usefulLinks\` |
| \`termsOfUseLink\` | the offer's terms / \`legal\` resource |

> Field names vary slightly by offer type - always trust \`resource-tree.json\` over this
> table. Images (logos, screenshots) are uploaded as listing **assets**; generate them in
> the wizard's Assets step and attach them to the listing resource.

## 3. Re-submit the listing resource

Wrap the edited listing resource in a \`configure\` envelope and POST it (the submit scripts
already show the POST + poll pattern), or paste the values directly in Partner Center.

## 4. Publish

\`\`\`bash
pwsh ./submit.ps1 -Target preview   # validate in preview
pwsh ./submit.ps1 -Target live      # go live after preview looks good
\`\`\`
`;
}

export async function buildSubmissionZip(ctx: SubmissionZipContext): Promise<Blob> {
  const zip = new JSZip();
  const root = zip.folder('partner-center-submission');
  if (!root) return zip.generateAsync({ type: 'blob' });

  root.file('configure.json', JSON.stringify(ctx.configurePayload, null, 2));
  root.file('listing-content.json', JSON.stringify(ctx.listingContent, null, 2));
  root.file('.env.example', SUBMISSION_ENV_EXAMPLE);
  root.file('submit.ps1', SUBMISSION_PS1);
  root.file('README.md', submissionReadme(ctx));
  root.file('MAPPING.md', submissionMapping(ctx));

  if (ctx.language === 'csharp') {
    const dir = root.folder('Submit');
    if (dir) {
      dir.file('Submit.csproj', SUBMISSION_CSPROJ);
      dir.file('Program.cs', SUBMISSION_PROGRAM_CS);
    }
  } else {
    root.file('submit.mjs', SUBMISSION_MJS);
    root.file('package.json', SUBMISSION_PACKAGE_JSON);
  }

  const workflows = root.folder('.github')?.folder('workflows');
  if (workflows) workflows.file('submit.yml', SUBMISSION_WORKFLOW_YML);

  return zip.generateAsync({ type: 'blob' });
}
